### ISSUE TITLE
Error while generating Screenshot

### ISSUE THREAD

**Issue by nikitsaraf** [adamn/python-webkit2png#48]
Here is the command I am trying to run to generate screenshot, and it is throwing some strange errors
```python
deploy:~$ DISPLAY=:99.0 webkit2png http://www.google.com -x 500 250
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/webkit2png/scripts.py", line 203, in __main_qt
TypeError: render_to_file() got an unexpected keyword argument 'url'
```

It throws the same error even after running the following command
```python
deploy:~$ xvfb-run --server-args="-screen 0 1024x768x24" python /usr/local/bin/webkit2png -o google.png http://www.google.com/
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/webkit2png/scripts.py", line 203, in __main_qt
TypeError: render_to_file() got an unexpected keyword argument 'url'
```
Any ideas, what I may be doing wrong ?

**Comment by Zigazou** [comment]
It seems that `scripts.py` is not synced with `webkit2png.py`.

It tries to call the `render_to_file` method with an argument called `url` where the definition of the method is `def render_to_file(self, res, file_object):`.

Until the bug is corrected, you can patch by editing line 203 of `webkit2png/scripts.py` and changing from:

    renderer.render_to_file(url=options.url, file_object=options.output)

to:

    renderer.render_to_file(res=options.url, file_object=options.output)
